SoftwareBrothers/adminjs

src/frontend/views/mixins/emptyTable.pug
Just minor edits to the user-facing empty table text.
=> Edit to empty table text

src/frontend/components/login/index.tsx
Added a form field attribute that disables autocomplete on the password field of the authenticated router.
.
The "off" value does not work on modern browsers but the "new-password" value does.
=> Added a form field attribute that disables autocomplete on the password field.

src/backend/bundler/config.js
Resolves:
[Issue #178 -  Custom components using third-party React libraries](https://github.com/SoftwareBrothers/admin-bro/issues/178)
=> Fix bundling Material UI components

src/frontend/components/app/breadcrumbs.tsx
I'm not sure if this code is correct. Are breadcrumbs used in any place where having a Dashboard link makes no sense?
=> Add Dashboard to breadcrumbs

src/admin-bro.spec.ts, src/admin-bro.ts, vendor-types/node/node.d.ts, yarn.lock
it fixes NoDatabaseAdapter found when you have different linked versions of packages
=> fix: move RegisteredAdapters to globak scope

src/backend/decorators/property-decorator.ts, src/backend/decorators/property-options.interface.ts
BREAKING CHANGE: name in propery options doesn't affect property anymore
closes #448
=> improvement: remove name from property options

cy/readme.md
=> - added cypress readme

src/backend/adapters/record/base-record.ts, src/backend/controllers/api-controller.spec.js, src/backend/decorators/resource/resource-decorator.ts, src/backend/decorators/resource/utils/flat-sub-properties.ts, src/backend/utils/populator/populate-property.spec.ts, src/backend/utils/populator/populate-property.ts, src/backend/utils/populator/populator.ts, src/frontend/hooks/use-record/filter-record.ts, src/utils/flat/flat.types.ts, src/utils/flat/get.spec.ts, src/utils/flat/get.ts, src/utils/flat/property-key-regex.ts, src/utils/flat/select-params.spec.ts, src/utils/flat/select-params.ts
this one fixes population for super nested properties
=> fix: population logic for deeply nested properties

.eslintrc.js, cy/commands/ab-get-property.js, cy/commands/ab-keep-logged-in.js, cy/commands/ab-login-api.js, cy/commands/ab-login.js, cy/index.d.ts, cy/index.js, package.json, packages/admin-bro-e2e/cypress/integration/companies/create-company.spec.js, packages/admin-bro-e2e/cypress/integration/companies/list-companies.spec.js, packages/admin-bro-e2e/cypress/integration/employees/create-employee.spec.js, packages/admin-bro-e2e/cypress/integration/external-employees/create-external-employee.spec.js, packages/admin-bro-e2e/cypress/integration/nested/create-nested.spec.js, packages/admin-bro-e2e/cypress/integration/pages/create-page.spec.js, packages/admin-bro-e2e/cypress/integration/professions/create-profession.spec.js, packages/admin-bro-e2e/cypress/integration/sign-in/sign-in.spec.js, packages/admin-bro-e2e/cypress/integration/taggables/edit-taggable.spec.js, packages/admin-bro-e2e/cypress/integration/tools/create-tool.spec.js, packages/admin-bro-e2e/cypress/integration/tools/edit-tool.spec.js, packages/admin-bro-e2e/cypress/integration/tools/list-tools.spec.js, packages/admin-bro-e2e/cypress/support/commands.js
First PR with the concept of having cypress inside the admin-bro package
=> #622/build and export cypress helpers

src/frontend/components/property-type/array/edit.tsx
#816 
Add encode with unescape in record value
=> fix: btoa encoding in array edit

src/backend/actions/action.interface.ts, src/backend/decorators/resource/utils/decorate-actions.ts
Closes https://github.com/SoftwareBrothers/adminjs/issues/858
=> fix: fix default ACTIONS hooks override not working

src/backend/actions/search/search-action.ts
Closes https://github.com/SoftwareBrothers/adminjs/issues/840
Closes https://github.com/SoftwareBrothers/adminjs/issues/972
=> feat: allow to specify custom filters and sorting for search action

src/utils/param-converter/convert-param.ts
This commit is fixing an issue related to `null` values for `Date` and `DateTime` fields
=> fix: fixed null value converting for dates

src/frontend/components/app/filter-drawer.tsx
=> fix: fixed filters autocomplete from url

bin/bundle-globals.js
Reverts SoftwareBrothers/adminjs#996
=> Revert "Update bundle-global file to include SCSS & fix issue with external n…"

tsconfig.json
=> TS - disabled lib check

src/adminjs.ts, src/backend/decorators/property/property-decorator.spec.ts, src/backend/decorators/property/property-decorator.ts, src/backend/decorators/property/property-options.interface.ts, src/backend/utils/view-helpers/view-helpers.ts, src/frontend/components/app/filter-drawer.tsx, src/frontend/components/property-type/utils/property-description/index.ts, src/frontend/components/property-type/utils/property-description/property-description.tsx, src/frontend/components/property-type/utils/property-label/property-label.tsx, src/frontend/interfaces/property-json/property-json.interface.ts, tsconfig.json
Closes https://github.com/SoftwareBrothers/adminjs/issues/807
Closes https://github.com/SoftwareBrothers/adminjs/issues/639
Closes https://github.com/SoftwareBrothers/adminjs/issues/781
Closes https://github.com/SoftwareBrothers/adminjs/issues/711
Closes https://github.com/SoftwareBrothers/adminjs/pull/969
=> Collective resolve of GitHub issues

src/utils/param-converter/prepare-params.ts
This commit is fixing an issue related to non-string values for Array fields
=> fix: fixed array value converting

src/backend/actions/list/list-action.ts
Closes https://github.com/SoftwareBrothers/adminjs-sequelizejs/issues/91
=> fix: list without sortable columns

.github/workflows/push.yml
Removed notifications from Git workflows
=> chore: Removed notifications

src/utils/param-converter/prepare-params.ts
This PR is a fix for issue #1056.
=> Allow non-editable array fields

src/frontend/components/routes/resource-action.tsx, src/frontend/components/routes/utils/wrapper.tsx
Closes https://github.com/SoftwareBrothers/adminjs/issues/1022
Filter button should now appear in resource actions if `showFilter: true` is set
=> fix: add Filter button to resource actions

package.json, src/frontend/components/app/records-table/record-in-list.tsx, src/frontend/interfaces/action/build-action-click-handler.ts
This returns a promise from button's click handler, but https://github.com/SoftwareBrothers/adminjs-design-system/pull/41 needs to be released and used before it works properly.
=> feat(small): show spinner when record action is clicked

src/adminjs.ts
=> Cannot set language ​​other than en or ua.

src/frontend/components/property-type/utils/property-description/property-description.tsx
feat: Make description tooltip direction customizable
=> Make description tooltip direction customizable

src/utils/param-converter/convert-nested-param.ts
continue the loop if the value is undefined.
=> Fix bug:  value is not iterable

src/backend/adapters/property/base-property.ts, src/frontend/components/property-type/base-property-component.tsx, src/frontend/components/property-type/key-value/edit.tsx, src/frontend/components/property-type/key-value/index.ts, src/frontend/components/property-type/key-value/show.tsx, src/locale/en.ts
https://user-images.githubusercontent.com/16668924/194540794-0054bdd2-e667-482f-a008-1e746fed3132.mov
=> feat: add key-value property type

src/backend/actions/bulk-delete/bulk-delete-action.ts, src/frontend/components/actions/bulk-delete.tsx
Hello ! 
First of all, thank you for this library. I really enjoy using it  in a project for my company :)
I have found few bugs about plural translations
Some are declared in locale files ( https://github.com/SoftwareBrothers/adminjs/blob/master/src/locale/en.ts ) but are never used
=> fix : plural for bulk delete

package.json, yarn.lock
Fixes https://github.com/SoftwareBrothers/adminjs/issues/1337
=> fix(deps): bump design system to resolve richtext errors

.github/workflows/push.yml
This reverts commit 8dd716e2a625741b9ed8800eb690b644f19dad8f.
=> fix: Revert "ci: fix warnings about deprecated actions"

README.md
Closes https://github.com/SoftwareBrothers/adminjs/issues/1387
=> chore: update README.md with information about RST and fix links

src/frontend/components/app/filter-drawer.tsx
fixes https://github.com/SoftwareBrothers/adminjs/issues/1581
=> fix: set page to 1 when applying filters

src/locale/es/translation.json
=> fix: Spanish translation

src/frontend/components/property-type/datetime/map-value.ts
Closes https://github.com/SoftwareBrothers/adminjs/issues/1691
=> fix: propertyType date should not convert to local timezone

src/backend/services/action-error-handler/action-error-handler.ts
Fixes https://github.com/SoftwareBrothers/adminjs/issues/1706
=> fix: fix ForbiddenError returning information about record
