SoftwareBrothers/adminjs

.gitignore
README.md

This small PR fixes link to LICENSE file. There is a `LICENSE.md` file but link in `README.md` was to `LICENSE` (without `.md`).
I also added to `.gitignore` config files from popular JetBrains IDE (phpstorm, webstorm).

LICENSE, IDE config files

---

package.json
yarn.lock

Fixes a security vulnerability in `rollup-plugin-terser`: https://www.npmjs.com/advisories/1426

Upgrade rollup-plugin-terser to fix security vulnerability

---

src/frontend/components/design-system/atoms/check-box.tsx
src/frontend/components/design-system/atoms/radio.tsx

Hooks cannot be used conditionally because React needs to track their order to work correctly. Having a hook that sometimes is called but other times isn't can lead to confusing bugs happening in random places.

Fix conditional hooks in radio and checkbox atoms

---

src/admin-bro.ts
src/backend/router.ts
src/backend/utils/view-helpers.ts

Fixed constructing invalid paths like `//frontend/[...]` by using `path.join()`
Resolves #272

Fix constructing url paths

---

src/frontend/components/property-type/reference/edit.tsx
src/frontend/hooks/use-record.tsx

When updating refs in `src/frontend/components/property-type/reference/edit.tsx` the record loaded from the backend is passed to the `onChange` function. This is supposed to update `populated` field in the original record with the loaded one, so it's kept in sync with ID in the `params`. It however has no effect, since `onChange` function originates in `useRecord` hook and does not accept a third argument.
This PR fixes that by adding logic for updating `populated` field with passed record.
It fails on `lint` script but that's also failing on master and fixing it is outside of this PR's scope.

Fix ref editing sometimes losing correct state

---

src/frontend/hooks/index.ts

This is needed for custom `list` actions.

Export useSelectedRecord hook

---

src/frontend/components/design-system/atoms/input.tsx

All other components have a white background, so I made regular inputs consistent. It's visible only when the background color of the custom `edit` action is different than white.

Make the input background white

---

src/frontend/components/property-type/reference/edit.tsx

Previously the `Edit` reference component only displayed the selected value when it was present in the `populated` field or was manually selected by the user. That is okay when editing fields or displaying them immediately after loading, assuming they're only one level deep. But AdminBro doesn't send `populated` fields for nested objects or objects in arrays. This means that for those properties the select displays no value even if it's actually correctly selected under the hood.
This PR converts `Edit` component to a function component and modifies it so that is uses the data loaded from the backend (which is already being used to fill the dropdown) to display currently selected option.

Fix reference selects being sometimes empty

---

src/backend/actions/search-action.ts

search-action now respect custom sortBy in decorated.options. ListAction.handler my also need to be updated. I'm not sure and don't know the code base well enough.
Please note these two tests failed on a windows system before and after the change.
163 passing (2s)
2 failing
1) generateUserComponentEntry
adds components to the entry file:
AssertionError: expected 'AdminBro.UserComponents = {}\nimport Component5 from \'spec/fixtures/example-component\'\nAdminBro.UserComponents.Component5 = Component5' to contain 'import Component5 from \'spec\\fixtures\\example-component\'\nAdminBro.UserComponents.Component5 = Component5'
at Context.<anonymous> (src\backend\bundler\generate-user-component-entry.spec.js:38:31)
at processImmediate (internal/timers.js:456:21)
2) Router
returns development …

fixes #435 - search-action now respect custom sortBy in decorated.options

---

src/frontend/components/app/breadcrumbs.tsx

The last breadcrumb wasn't displayed on `new` action as well as on custom actions defined by user.

Display breadcrumbs on actions without record

---

src/frontend/components/property-type/datetime/edit.tsx

Add [`showYearDropdown`](https://reactdatepicker.com/#example-year-dropdown) option to [react-datepicker](https://www.npmjs.com/package/react-datepicker)
It helps the usability of the date component to select a date in the past, or in the future (without resorting to editing the input value directly)

Show dropdown for year selection

---

example-app/cypress/integration/external-employees/create-external-employee.spec.js
example-app/models/externalemployees.js
src/frontend/components/design-system/molecules/date-picker.tsx
src/frontend/components/property-type/datetime/edit.tsx

Pass the `property.type` (as `propertyType` prop) to the `DatePicker` component to show the relevant format for date (only) types

fix: show date (only) format without time

---

src/frontend/components/design-system/molecules/date-picker.tsx

After https://github.com/SoftwareBrothers/admin-bro/pull/512 I noticed everything is pushed down a few pixels in the year dropdown, due to the style override. Therefore the upcoming year navigation is overlapping the list of years
Before:
After:

fix: datepicker style overwrite for year selection

---

src/backend/actions/action.interface.ts

Fix a typo in "array wf widths" where wf should be of

docs: typo

---

src/frontend/components/design-system/molecules/date-picker.tsx
src/frontend/components/property-type/datetime/edit.tsx

Currently the [`DatePicker`](https://github.com/SoftwareBrothers/admin-bro/blob/62bad1d3d83401a700dd6d5dac4c65c7307da87d/src/frontend/components/design-system/molecules/date-picker.tsx#L112-L129) component type definition doesn't allow custom props to be passed down, even though [the code](https://github.com/SoftwareBrothers/admin-bro/blob/62bad1d3d83401a700dd6d5dac4c65c7307da87d/src/frontend/components/design-system/molecules/date-picker.tsx#L198) would allow it.
From what I understand (correct me if I'm wrong here), simply adding this to the arguments type definition:
```
[key: string]: any;
```
would allow to pass props to the `DatePicker` component, which would then be passed to the [`react-datepicker`](https://reactdatepicker.com/)
The reason for doing this is simple, if someone …

feat: accept extra props on DatePicker to pass down

---

src/frontend/components/property-type/default-type/edit.tsx
src/frontend/components/property-type/password/edit.tsx
src/frontend/components/property-type/richtext/edit.tsx
src/frontend/components/property-type/textarea/edit.tsx
src/frontend/utils/loadQuill.ts
src/frontend/utils/usePrevious.ts
vendor-types/quill/index.d.ts
yarn.lock

This makes inputs only commit changes when they loose focus, instead of on every key press. This eliminates the janky feeling when typing in huge records while on a relatively slow device.

Improve performance of text inputs

---

.eslintrc.js
example-app/package.json
src/frontend/components/app/sidebar/sidebar-resource.tsx
src/frontend/components/app/sidebar/sidebar.tsx
src/frontend/components/application.tsx
src/frontend/hooks/use-sidebar.ts
src/frontend/store/actions/sidebar.ts
src/frontend/store/store.ts
src/frontend/utils/isMobileDevice.ts

Fix for #601.
Sidebar state is now controlled on Redux State.
Created a React Hook for Sidebar that can be called anywhere

fix: [#601] Sidebar state is now stored in Redux Store

---

src/admin-bro.ts

fixes #592 
you still need to put initializing admin-bro into the success callback of i18n to work together:
```js
const loadAdminBro = () => {
const { adminBro, adminRouter } = admin()
app.use(adminBro.options.rootPath, adminMiddleware, adminRouter)
app.use('/admin', adminMiddleware, adminController)
}
i18next.init({...}, (err, t) => {
loadAdminBro()
})
```
but then works like a charm :D

fix: initialize i18n only if its not already, extend otherwise

---

src/utils/flat/get.ts

Fixes https://github.com/SoftwareBrothers/admin-bro/issues/695
This does fix the issue and I can confirm it now works with even more complex arrays, i. e. array of values and nested arrays of values and references (tested using mongoose adapter and https://github.com/SoftwareBrothers/admin-bro-example-app).
The problem was that the regex for selecting siblings expected the temp key to have an index after delimiter but it didn't.
Test schemas:
Thing
```
module.exports = mongoose.model('Thing', {
name: String,
users: [{
role: String,
userId: {
type: mongoose.ObjectId,
ref: 'User',
},
}],
tests: [{
xyz: String,
nested: [new mongoose.Schema({ value: String, userId: { type: mongoose.ObjectId, ref: 'User' } })]
}]
})
```
User
```
const mongoose = require('mongoose')
const { Schema } = mongoose …
```

[Fix] Fix populating arrays of references

---

src/frontend/login-template.tsx

This pull request parses the scripts and styles arguments passed to the AdminBro constructor for display on the login page. This will allow basic style overrides using a custom stylesheet.
Would probably allow you to close the following issues:
https://github.com/SoftwareBrothers/admin-bro/issues/347
https://github.com/SoftwareBrothers/admin-bro/issues/531
To use custom styles on the login page:
```javascript
new AdminBro({
assets: {
styles: ['/some-stylesheet.css'],
}
});
```

feat: pass custom styles and scripts to login template

---

src/frontend/components/actions/utils/append-force-refresh.spec.ts
src/frontend/components/actions/utils/append-force-refresh.ts

This fixes an issue where, i. e.:
1. You are in a list view of resource `X` with filters applied.
2. You run a custom action with redirect to another resource (`Y`).
3. The action works, but filters from resource `X` are applied and the redirect results in error.
If you add `ignore_params=true` in your custom action's redirect search params, it will ignore old search params when redirecting in frontend:
```
return {
redirectUrl: h.resourceUrl({
resourceId: resource._decorated
? resource._decorated.id()
: resource.id(),
search: '?ignore_params=true',
}),
record: context.record.toJSON(currentAdmin),
};
```

[Fix] Add `ignore_params` search param handling to ignore old params in redirect URLs

---

src/frontend/components/property-type/mixed/convert-to-sub-property.ts

This looks to work, I tested it with Sequelize and Mongoose adapters using simple and complex nested schemas. `subProperty.name` contained a full path which caused it to be merged incorrectly when building record params.

[Fix] Fix an issue where `mixed` type would add an additional nesting layer

---

src/frontend/interfaces/action/build-action-click-handler.ts

History API doesn't update `document.referrer` so it's impossible to know what page user navigated from.
This change stores previous page link in `location.state`. In my specific use case I needed it to be able to get `list` action filters and pass them to another resource action.

feat: store previous page url in location state when navigating

---

package.json
yarn.lock

This PR sets `i18next` to use fixed version `19.8.7`, more here: https://github.com/i18next/i18next/issues/1570
The change should later be reverted once the issue gets fixed in `i18next` or another solution is found.

fix: fix a bug where translations would be missing after logging in

---

src/backend/actions/new/new-action.ts
src/backend/adapters/record/base-record.ts

I've noticed the [`save`](https://github.com/SoftwareBrothers/admin-bro/blob/907d03c7ed8f01ca5027655599faabad5c0f6d8c/src/backend/adapters/record/base-record.ts#L155
) method on record is really only called when a record is being created via the [`new`](https://github.com/SoftwareBrothers/admin-bro/blob/907d03c7ed8f01ca5027655599faabad5c0f6d8c/src/backend/actions/new/new-action.ts#L34) handler.
The [`edit`](https://github.com/SoftwareBrothers/admin-bro/blob/907d03c7ed8f01ca5027655599faabad5c0f6d8c/src/backend/actions/edit/edit-action.ts#L42) handler instead calls `record.update()` directly.
Therefore I was wondering why the [check for id](https://github.com/SoftwareBrothers/admin-bro/blob/907d03c7ed8f01ca5027655599faabad5c0f6d8c/src/backend/adapters/record/base-record.ts#L158-L162
) in …

fix: remove resource.update() call in record.save()

---

src/backend/decorators/resource/resource-decorator.spec.ts
src/backend/decorators/resource/resource-options.interface.ts
src/backend/decorators/resource/utils/get-navigation.spec.ts
src/backend/decorators/resource/utils/get-navigation.ts
src/backend/utils/build-feature/build-feature.spec.ts
src/backend/utils/build-feature/build-feature.ts
src/frontend/components/spec/resource-json.factory.ts
src/frontend/hooks/use-navigation-resources.ts
src/frontend/interfaces/resource-json.interface.ts

Adds a new variant to the navigation option for resources to specify that a resource should not be visible in the nav bar on the side. Resources can still have actions and are still clickable from references in other resources.
Fixes #749
Example usage:
```
const adminBro = new AdminBro({
resources: [
{
resource: InternalModel,
options: {
navigation: false
}
},
]
})
```

feat: add navigation: false option to hide resource from nav bar

---

src/frontend/components/actions/new.tsx

Currently if an `id` field is specified on creation (new action), the returned record object also has the `id` field, and the code behaves as if the record was created – even when an error occured.
To try to determine if the object was indeed created, I am suggesting to add a check for errors. This would assume that the errors are triggered before creating the record. As if the record is created but the error triggered after, the expected behavior is unclear.
If a record has been created, but the error is triggered afterwards, this change would affect the current behavior. Currently the data on the form is being cleared, and it is possible to create a new record. Even though errors are returned, they are not shown. Whereas after this change, the form will keep the data and the errors will …

fix: only treat records as new after submit if no errors

---

src/frontend/components/property-type/default-type/edit.tsx

add required attribute to the input and not only to the label ...
This will fix the bug where `isRequired` property will block (html5) form submit for required fields
see issue #690

make required attributes work the front end (solved issue #690)

---

src/adminjs.ts

Calling `AdminJS.bundle` with an absolute path fails on windows, because the code that checks if the path is absolute doesn't work with windows paths, which start with drive letters.
Using `path.isAbsolute` from nodeJS fixes this.
The error my colleague was getting:
We tried this fix locally with [patch-package](https://www.npmjs.com/package/patch-package), and it fixed the crash.

Fix AdminJS.bundle on windows

---

src/adminjs.ts

```
properties: {
text: {
components: {
edit: AdminJS.bundle('../custom/components/VisualEditor.tsx'),
}
}
}
```
In this case filename (src/adminjs.ts:316) is absolute_path/custom/components/VisualEditor.tsxnull

fix: remove null from bundle extension

---

src/backend/adapters/property/base-property.ts
src/frontend/components/property-type/base-property-component.tsx
src/frontend/components/property-type/currency/edit.tsx
src/frontend/components/property-type/currency/filter.tsx
src/frontend/components/property-type/currency/format-value.ts
src/frontend/components/property-type/currency/index.ts
src/frontend/components/property-type/currency/list.tsx
src/frontend/components/property-type/currency/show.tsx
src/frontend/components/property-type/index.tsx

Requested in https://github.com/SoftwareBrothers/adminjs-design-system/issues/32
Currency input introduced in `design-system` with https://github.com/SoftwareBrothers/adminjs-design-system/pull/35
Demo available on https://github.com/SoftwareBrothers/adminjs-example-app/pull/41
**Example**
```ts
// resource
options: {
properties: {
price: {
type: "currency",
props: {
intlConfig: { locale: "de-DE", currency: "EUR" },
},
},
},
},
```
**Create**
**Filter**
**Show**
**List**

feat: Currency input

---

src/adminjs-options.interface.ts
src/backend/utils/view-helpers/view-helpers.ts
src/core-scripts.interface.ts
src/frontend/layout-template.tsx
src/frontend/login-template.tsx

Example: https://github.com/SoftwareBrothers/adminjs-example-app/pull/44
`@adminjs/bundler` can help with versioning: https://github.com/SoftwareBrothers/adminjs-bundler/pull/3

feat: allow to version admin bundle assets

---

src/backend/actions/action.interface.ts
src/backend/decorators/action/action-decorator.ts
src/frontend/components/app/action-header/action-header.tsx
src/frontend/components/spec/action-json.factory.ts
src/frontend/interfaces/action/action-json.interface.ts

The purpose is to introduce a configurable option to hide resource actions button at the top of the action's UI (top-right corner). An example is that you e. g. have an action called `Export CSV` which is a `resource` action. It is misleading to display it in `show` or `edit` UI because it exports all/filtered records and not a specific record.

fix: add 'showResourceActions' to action config

---

package.json
src/frontend/components/app/action-header/action-header.tsx

This might not be 100% required because it's mostly to satisfy types and create a feature changelog, but `@adminjs/design-system` `v>=2.2.4` is needed though.

feat(small): show spinner when record action in header is clicked

---

src/backend/actions/delete/delete-action.spec.ts
src/backend/actions/delete/delete-action.ts
src/backend/actions/edit/edit-action.ts
src/backend/actions/new/new-action.ts
src/backend/adapters/record/base-record.spec.ts
src/backend/adapters/record/base-record.ts
src/backend/decorators/action/action-decorator.spec.ts
src/backend/services/action-error-handler/action-error-handler.spec.ts
src/backend/services/action-error-handler/action-error-handler.ts
src/frontend/components/spec/record-json.factory.ts
src/frontend/hooks/use-record/update-record.spec.ts
src/frontend/interfaces/record-json.interface.ts

Added some error handling improvements to better support API based adapters, which may return validation or forbidden errors.
* Added a baseError property to the BaseRecord.
* This allows any ValidationError baseError messages to be stored in the record and then used when generating the notice error for the Edit and New backend actions.
* Fixed the logic for handling ValidationErrors in the Delete backend actions, so it no longer requires a baseError to generate a notice error response.
* Added new Delete backend actions test spec to validate the above change.
* Updated the default backend Action Error Handler to return all required values for displaying an error notice in the frontend for the List backend action and for ForbiddenErrors
Added and updated automated unit testing to cover …

Improved ValidationError and ForbiddenError handling in backend

---

package.json
src/frontend/components/property-type/array/edit.tsx
yarn.lock

`@react-forked/dnd` is now [@hello-pangea/dnd](https://github.com/hello-pangea/dnd). This PR switches to the new name.
The original developer of `@react-forked/dnd` and myself are now collaborating on maintaining the library and felt the Pangea name would serve us better going forward. See https://github.com/hello-pangea/dnd/issues/408 for more details.
Let me know if you have any questions 👍

chore: use @hello-pangea/dnd

---

src/backend/utils/router/router.ts

Remove the trailing slash from the `/api/resources/{resourceId}/search` path to not conflict with Hapi projects using the `stripTrailingSlash` on `true`, and also to have all the paths with the same format.

fix: remove the trailing slash from the resources search path

---

src/adminjs.ts
src/backend/utils/component-loader.ts

This removes add/override checks from `AdminJS.bundle()` calls so the component name argument can be used for custom components.
Previously it would try to use `loader.override()` method if the name was provided, causing an error when the name was not on the list of overridable components.

fix: error in AdminJS.bundle() compatibility

---

src/adminjs.ts

The bug is caused by missing `ComponentLoader` when the features are being loaded into resources. The fix moves `ComponentLoader` initialization ahead of feature loading.

fix: feature component loader issue

---

src/backend/actions/action.interface.ts
src/backend/actions/bulk-delete/bulk-delete-action.ts
src/backend/actions/delete/delete-action.ts
src/backend/actions/new/new-action.ts
src/backend/actions/show/show-action.ts
src/backend/bundler/config.js
src/backend/decorators/resource/utils/get-navigation.spec.ts
src/backend/decorators/resource/utils/get-navigation.ts
src/frontend/components/actions/bulk-delete.tsx
src/frontend/components/actions/edit.tsx
src/frontend/components/actions/new.tsx
src/frontend/components/app/action-header/action-header.tsx
src/frontend/components/app/base-action-component.tsx
src/frontend/components/app/logged-in.tsx
src/frontend/components/app/records-table/no-records.tsx
src/frontend/components/app/records-table/record-in-list.tsx
src/frontend/components/app/sort-link.tsx
src/frontend/components/property-type/array/add-new-item-translation.tsx
src/frontend/components/property-type/array/edit.tsx
src/frontend/components/property-type/key-value/edit.tsx
src/frontend/components/property-type/password/edit.tsx
src/frontend/components/property-type/utils/property-description/property-description.tsx

BREAKING CHANGE: Carbon Icons have been replaced by Feather Icons, a lighter icons library, to reduce the bundle size of @adminjs/design-system. There are less icons and their names are often different than Carbon's. If you were using the Icon component imported from @adminjs/design-system, make sure you update icon names to their counterparts from https://feathericons.com/. You can still install other icon libraries and use them in your custom components, take note of the bundle size though.

feat: replace icons library

---

src/backend/actions/bulk-delete/bulk-delete-action.ts
src/backend/actions/delete/delete-action.ts
src/backend/actions/edit/edit-action.ts
src/backend/actions/list/list-action.ts
src/backend/actions/new/new-action.ts
src/backend/actions/search/search-action.ts
src/backend/adapters/record/base-record.ts
src/backend/adapters/resource/base-resource.ts
src/backend/controllers/api-controller.ts
src/backend/utils/filter/filter.ts
src/backend/utils/populator/populate-property.ts
src/backend/utils/populator/populator.ts

Closes #1353
Is backwards compatible, adapters do not need to use `currentAdmin` if they don't need it

feat: include context when calling adapter functions

---

src/backend/actions/action.interface.ts

Motivation behind this change is fact, that `Before` action return type strictly enforces  to use async. 
It would be great to  also enable returning `ActionRequest` synchronously.

feat: extended return type of Before action by ActionRequest

---

src/backend/actions/action.interface.ts

Could we extend `ActionHandler` type to allow synchronous actions? I believe `before` and `after` handlers have already been updated in a similar fashion.

feat: extend ActionHandler return type

---

src/frontend/components/property-type/array/edit.tsx

Set wrapper of array property with variant transparent. Array property can be tested in demo app in `Mongoose -> Complicated` resource.
**Light theme:**
**Dark theme:**

style: fixed array property background in dark mode

---

src/frontend/interfaces/action/build-action-click-handler.ts

There was unable to create a custom resource action without a component and guard.
For this configuration, I always get an error: "You have to implement action component for your Action".
```
actionWithoutComponent: {
actionType: 'resource',
component: false,
handler: () => {
return () => ({
notice: {
message: 'Test',
type: 'success',
},
});
},
},
```
I decided to fix that 😊

fix: unable to create custom resource action without component

---

src/frontend/components/actions/bulk-delete.tsx
src/frontend/components/actions/edit.tsx
src/frontend/components/actions/list.tsx
src/frontend/components/actions/new.tsx
src/frontend/components/actions/show.tsx
src/frontend/components/app/action-button/action-button.tsx
src/frontend/components/app/action-header/action-header.tsx
src/frontend/components/app/action-header/styled-back-button.tsx
src/frontend/components/app/breadcrumbs.tsx
src/frontend/components/app/filter-drawer.tsx
src/frontend/components/app/logged-in.tsx
src/frontend/components/app/notice.tsx
src/frontend/components/app/records-table/no-records.tsx
src/frontend/components/app/records-table/property-header.tsx
src/frontend/components/app/records-table/record-in-list.tsx
src/frontend/components/app/records-table/records-table-header.tsx
src/frontend/components/app/records-table/records-table.tsx
src/frontend/components/app/records-table/selected-records.tsx
src/frontend/components/app/sidebar/sidebar-branding.tsx
src/frontend/components/app/sidebar/sidebar-footer.tsx
src/frontend/components/app/sidebar/sidebar-pages.tsx
src/frontend/components/app/sidebar/sidebar-resource-section.tsx
src/frontend/components/app/sidebar/sidebar.tsx
src/frontend/components/app/top-bar.tsx
src/frontend/components/app/version.tsx

This PR fixes a bug which prevented you from importing an original component, modifying the props and returning the original component with modified props.
Example:
```typescript
import React from 'react';
import { OriginalRecordInList, RecordInListProps } from 'adminjs';
const RecordInListOverride: React.FC<RecordInListProps> = (props) => {
const { resource, record } = props;
// If resource is different than SomeResource, return original component
if (resource.id !== 'SomeResource') {
return <OriginalRecordInList {...props} />;
}
const updatedProps = {
...props,
record: {
...record,
recordActions: record.recordActions.filter((a) => a.name !== 'show'),
},
};
// Else modify props so that "show" action is not available
return <OriginalRecordInList {...updatedProps} />;
};
export default …
```

fix: allow to import original components without HOC-loop

---

src/backend/actions/delete/delete-action.ts
src/frontend/components/app/error-message.tsx
src/frontend/components/routes/record-action.tsx
src/frontend/components/routes/resource-action.tsx
src/frontend/interfaces/action/action-has-component.ts
src/frontend/interfaces/action/build-action-click-handler.ts
src/frontend/interfaces/action/call-action-api.ts

Resolves:
https://github.com/SoftwareBrothers/adminjs/issues/1507
https://github.com/SoftwareBrothers/adminjs/issues/1447
as a temporary workaround.
`delete` action now performs an actual delete only if `request.method` is `post`. Other potentially destructive built-in actions (`new`, `edit`, `bulkDelete`) have already differentiated between `get` and `post`. In version 8 we should rewrite action buttons & click handlers so that "default method" for action can also be configured. We should also introduce `PATCH`, `PUT` and `DELETE` request methods but this also comes with breaking changes. When adding new custom actions, you should add `if (request.method === 'xxx')` checks at the start to avoid destructive behaviours.
Additionally, when you enter a route for an action that has it's …

Resolve actions issues

---

src/backend/decorators/property/property-options.interface.ts
src/backend/decorators/resource/resource-decorator.ts
src/backend/decorators/resource/resource-options.interface.ts
src/backend/utils/build-feature/build-feature.ts

Resolves https://github.com/SoftwareBrothers/adminjs/issues/568

feat: allow to set titleProperty in resource options

---

src/backend/utils/component-loader.ts

When using AdminJS with CommonJS projects (like NestJS), the only way I could have custom React components working has been by putting them into `.mjs` files (this unfortunately loses typing as [TypeScript doesn't support `.mtsx`](https://github.com/microsoft/TypeScript/issues/44442), but that's how it is...)
Currently, `ComponentLoader` doesn't allow this file extension, but I don't think there is any problem by allowing them? It worked for me at least, so here is the change :)

fix: allow bundling .mjs and .mts files via ComponentLoader

---

src/frontend/components/property-type/reference/reference-value.tsx

Explain issue:
I'm facing an issue with a resource list. The error message reads: "TypeError: Cannot read properties of undefined (reading 'find')." I have attached an image for more details. 
I suspect that the issue is due to a removed relationship.
"@adminjs/express": "^6.0.1",
"@adminjs/mongoose": "^4.0.0",
"adminjs": "^7.5.2",

fix: list action populate issue

---

src/backend/bundler/user-components-bundler.ts

Skip generating the entry file and calling mkdir if not needed.

fix: return existing bundle immediately

---

src/backend/utils/view-helpers/view-helpers.ts
src/frontend/utils/api-client.ts

Thank you for such an amazing piece of software.
This PR fixes two small issues that prevent AdminJS from working on Deno.
AdminJS assumes that the environment is either a browser or NodeJS, only.
```sh
user@host ~/d/b/adminjs-deno (main)> deno task dev                                          (base) 
Task dev deno run --watch -A src/app.ts
Watcher Process started.
error: Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'isOnServer')
at Function.getBaseUrl (file:///Users/user/dev/brickpop/adminjs-deno/node_modules/.deno/adminjs@7.6.0/node_modules/adminjs/lib/frontend/utils/api-client.js:104:19)
at new ApiClient (file:///Users/user/dev/brickpop/adminjs-deno/node_modules/.deno/adminjs@7.6.0/node_modules/adminjs/lib/frontend/utils/api-client.js:98:30)
at …
```

Making adminjs work on Deno

---

src/backend/decorators/resource/resource-decorator.ts

This change allows setting a sub property as a title of resource.
For example:
```ts
resource: {
model: getModelByName('Sport'),
client: prisma,
},
options: {
titleProperty: 'translation.en',
listProperties: ['translation.ja', 'translation.en'],
properties: {
translation: { type: 'mixed' },
'translation.ja': { type: 'string' },
'translation.en': { type: 'string' },
// some other props
},
},
```
In master branch such `titleProperty` is just ignored which is an unexpected behavior.

feat: support subproperties as a title

---

.babelrc.json
.github/workflows/push.yml
src/locale/index.ts

Resolves `SyntaxError: Unexpected identifier 'assert'` in Node.js 22.
Closes #1663

fix: running with Node.js 22

---

.cspell.json
src/utils/file-resolver.ts

When importing a [custom component](https://docs.adminjs.co/ui-customization/writing-your-own-components) on the Windows platform, there was a problem with determining the path. This PR also fixes the problem with the Cyrillic alphabet in the file path.
Before:
\D:\%D0%9D%D0%B8%D0%BA%D0%B8%D1%82%D0%B0\project\dist\components\photo
After:
D:\Никита\project\dist\components\photo

fix: incorrect file path in Windows platform

---

src/frontend/components/property-type/datetime/edit.tsx

Similar to #1692 but for the edit component. 
Should have no impact on `date-time` component as that was already working correctly.

fix: propertyType date edit should not convert to local timezone

---

src/frontend/components/property-type/datetime/edit.tsx
src/frontend/components/property-type/datetime/map-value.ts
src/frontend/components/property-type/datetime/strip-time-from-iso.ts

Fixes issue related to https://github.com/SoftwareBrothers/adminjs/issues/1691
@AshotN this fixes a bug where date values were rendered as `NaN-NaN-NaN` if backend returned an ISO string instead of a simple date string while having the property's `type` set to `date` instead of `datetime`.

fix: fix property type 'date' when backend returns an iso string

---

.github/workflows/push.yml

v3 of the artifact actions is no longer supported.

chore: fix workflow
